build:
  test:
    image: node:8
    commands:
      - yarn --no-lockfile
      - yarn test

# notify:
#   downstream:
#     repositories:
#       - buildo/react-components
#     token: $$NOTIFY_BRC_TOKEN
#     fork: true
#     when:
#       branch: master

cache:
  mount:
    - /drone/.npm
